name: Java CI - Academic Events CRUD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verifica o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Seta a JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' 
          
      # Limpa o cache das dependências Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Maven build e gera o relatório do JaCoCo
      - name: Build and test with Maven, including JaCoCo
        run: mvn clean verify --file pom.xml

      # SonarCloud Scan
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar \
          -Dsonar.projectKey=BrunoFelix1_academic-events-crud \
          -Dsonar.organization=brunofelix1 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
